✨ main screen insertion
VirtualSketch/vs-mobile-app pull request #11
Opened 2022-08-16 22:03 UTC by JorgeFernandoCR

2022-08-19 00:09 UTC, feykke approved these changes, later dismissed

2022-08-19 00:10 UTC, Leonardo-sm submitted a review, later dismissed

2022-08-20 12:52 UTC, JorgeFernandoCR reviewed
because the feature/history was created which already has the history components

2022-08-20 13:08 UTC, NickKlementiev approved these changes, later dismissed

2022-08-20 19:16 UTC, feykke approved these changes, later dismissed

2022-08-21 13:28 UTC, Leonardo-sm requested changes

2022-08-21 13:28 UTC, Leonardo-sm commented on lib/view/home_view.dart
> +                                '\r \r \r  SWIPE UP \n to open the menu',
Aqui ao invés de usar \r para quebrar a linha é melhor separar em outros Text

2022-08-21 23:17 UTC, JorgeFernandoCR reviewed
Feito

![imagem_2022-08-21_201728475](https://user-images.githubusercontent.com/101607473/185815003-e36ca976-88bc-40b9-8acd-8db88f0ee315.png)

2022-08-21 23:25 UTC, Leonardo-sm approved these changes

2022-08-23 01:07 UTC, NickKlementiev approved these changes

2022-08-26 01:52 UTC, feykke approved these changes

2022-08-26 01:54 UTC, merged