Inserção do Botão
VirtualSketch/vs-mobile-app pull request #7
Opened 2022-08-15 00:21 UTC by JorgeFernandoCR

2022-08-15 00:33 UTC, Leonardo-sm requested changes

2022-08-15 00:33 UTC, Leonardo-sm commented on lib/components/circle_button.dart
> +            );*/
Remover o comentário

2022-08-15 00:33 UTC, Leonardo-sm commented on lib/components/circle_button.dart
> +            color: Colors.white,
Colocar o branco do tema

2022-08-15 00:33 UTC, Leonardo-sm commented on lib/components/comp_home.dart
> +          CircleButton(),
juntar o circulo com este componente porque não faz sentido consonantizar algo que só é usado aqui e que não possui logica

2022-08-15 00:33 UTC, Leonardo-sm commented on lib/components/comp_home.dart
> +class CompHome extends StatelessWidget {
renomear de CompHome para SplashScrean já que esse componente não é a home

2022-08-16 18:46 UTC, JorgeFernandoCR reviewed
Feito todas as alterações pedidas

2022-08-16 18:46 UTC, JorgeFernandoCR commented on lib/components/circle_button.dart
> +            );*/
Removido

2022-08-16 18:46 UTC, JorgeFernandoCR commented on lib/components/circle_button.dart
> +            color: Colors.white,
Aplicado de acordo com o Figma

2022-08-16 18:46 UTC, JorgeFernandoCR commented on lib/components/comp_home.dart
> +class CompHome extends StatelessWidget {
Feito

2022-08-16 18:46 UTC, JorgeFernandoCR commented on lib/components/comp_home.dart
> +          CircleButton(),
Feito meu querido

2022-08-20 02:10 UTC, closed without merging